const projects = [
  {
    id: 1,
    imgLink: require('../img/project1.png'),
    title: "Resource Sharing Portal",
    description: "Resource sharing portal is a Web Application that provides a one-stop platform to the students for easy management of resources and course materials. It is a full-stack application implemented using the Django Framework.",
    stack: ["Python", "Django", "CSS", "Bootstrap", "SQLite"],
    githubLink: "https://github.com/Omanshu840/Resource-Sharing-Platform",
    Link: "https://omanshu840.pythonanywhere.com/",
  },
  {
    id: 2,
    imgLink: require('../img/project2.png'),
    title: "O-Meets: A Video Calling Platform",
    description: "A Web Application that facilitates video conferencing by implementing WebRtc architecture(Peer to Peer) with dynamic chat room support. NodeJs framework is used in the implementation.",
    stack: ["Node", "Express", "WebRTC", "Socket.io", "JavaScript","HTML", "CSS"],
    githubLink: "https://github.com/Omanshu840/Video-Calling-Platform",
    Link: "https://o-meets.herokuapp.com/",
  },
  {
    id: 3,
    imgLink: require('../img/project3.png'),
    title: "Mood Based Movie Recommender",
    description: "A Web Application that recommends movies by analyzing the facial expressions of the user. I worked on CNN Model with Keras and Backend of the Web Application with Flask Framework.",
    stack: ["Python", "Keras", "Flask", "HTML", "CSS", "MYSQL"],
    githubLink: "https://github.com/Omanshu840/Movie-Recommender",
    Link: "https://www.youtube.com/watch?v=n9FIgEeSloE",
  },
  {
    id: 4,
    imgLink: require('../img/project4.png'),
    title: "OS Simulator",
    description: "A Web Application that simulates various activities executed by the Operating System. I worked on UI/UX design and the Back-end of the application with the Django Framework.",
    stack: ["Python", "Django", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/OS-Simulator",
    Link: "#",
  },
  {
    id: 5,
    imgLink: require('../img/project5.png'),
    title: "Socio-Engage: Social Media Web App",
    description: "A social media Web Application built in MERN stack. It supports various functionalities, including User Authentication,  Creating Posts, Following existing users.",
    stack: ["NodeJs", "ReactJs", "MongoDB", "Express", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/MERN-Social-Media-App",
    Link: "https://socio-engage.herokuapp.com/",
  },
  {
    id: 6,
    imgLink: require('../img/project6.png'),
    title: "Mysuru Tourism Website",
    description: "Mysuru Tourism Web Application was built for the DSCWOW Hackathon organized by the Developer Students Club. It focuses on the travelers visiting Mysuru and provides them a brief guide of Mysuru tourism. The Application was built using the ReactJs frontend library with Firebase serving as the cloud database.",
    stack: ["ReactJs", "Firebase", "Dialogflow", "HTML", "CSS", "JavaScript", "Bootstrap"],
    githubLink: "https://github.com/Omanshu840/DSCWOW_DeltaG_Mysuru_Tourism",
    Link: "https://mysuru-tourism.herokuapp.com/",
  },
  {
    id: 7,
    imgLink: require('../img/project7.png'),
    title: "Extraction of Crop Cycle Parameters",
    description: "A Web Application that implements an algorithm to extract the crop cycle parameters for a given set of multispectral multi-temporal data. It was built for the Smart India Hackathon 2020.",
    stack: ["Python", "Flask", "OpenCV", "HTML", "CSS"],
    githubLink: "https://github.com/SIH-NITK/Hex-Clan",
    Link: "https://github.com/Omanshu840/SIH2020_Internal",
  },
]

export default projects;